src/main/java/lt/alna/entities/Person.java
package lt.alna.entities;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(name = "PERSON")
public class Person {

	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;

	private String name;
	private String surname;
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date birthday;

	public Person(){};
	
	public Person(String name, String surname, Date birthday) {
		super();
		this.name = name;
		this.surname = surname;
		this.birthday = birthday;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getBirthday() {
		return birthday;
	}

	public String getFormattedBirthday() {
		SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
		String date = "";

		if (birthday != null) {
			date = dt.format(birthday);
		}

		return date;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Override
	public String toString() {
		return "Person [id=" + id + ", name=" + name + ", surname=" + surname
				+ ", birthday=" + birthday + "]";
	}

}

src/main/java/lt/alna/controllers/PersonController.java
package lt.alna.controllers;

import lt.alna.entities.Person;
import lt.alna.services.PersonService;

import org.hibernate.annotations.common.util.impl.LoggerFactory;
import org.jboss.logging.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * Handles requests for the application home page.
 */
@Controller
public class PersonController {
	private static final Logger logger = LoggerFactory
			.logger(PersonController.class);
	@Autowired
	private PersonService personService;

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String listPersons(Model model) {
		model.addAttribute("person", new Person());
		model.addAttribute("findAll", this.personService.findAll());
		return "home";
	}

	// For add and update person both
	@RequestMapping(value = "/add", method = RequestMethod.POST)
	public String addPerson(@ModelAttribute("person") Person p) {
		if (p.getId() == 0) {
			// new person, add it
			this.personService.create(p);
		} else {
			// existing person, call update
			this.personService.update(p);
		}

		return "redirect:/";
	}

	@RequestMapping("/remove/{id}")
	public String removePerson(@PathVariable("id") int id) {
		this.personService.delete(id);
		return "redirect:/";
	}

	@RequestMapping("/edit/{id}")
	public String editPerson(@PathVariable("id") int id, Model model) {
		Person person = this.personService.findById(id);
		model.addAttribute("person", person);
		model.addAttribute("findAll", this.personService.findAll());
		model.addAttribute("findPersonRelatives", this.personService
				.findRelativesBy(findSurnamePattern(person.getSurname())));
		return "home";
	}

	/**
	 * Finds surname root pattern excluding Lithuanian endings and without
	 * Lithuanian symbols. If surname doesn't have Lithuanian ending, full
	 * surname is returning.
	 * 
	 * @param surname
	 *            to find root pattern
	 * @return surname pattern
	 */
	private String findSurnamePattern(String surname) {
		String surnamePattern = "";
		String[] surnameEndsArray = { "iene", "yte", "aite", "is", "ius",
				"iute", "as", "e", "a" };

		for (String endString : surnameEndsArray) {

			if (surname.endsWith(endString)) {
				surnamePattern = surname.substring(0, surname.length()
						- endString.length());
				logger.info("Found surname end: " + endString
						+ ". surname pattern: " + surnamePattern);
				return surnamePattern;
			}
		}
		
		return surname;
	}

	public void setPersonService(PersonService ps) {
		this.personService = ps;
	}

}

src/main/webapp/WEB-INF/views/home.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ page session="false" %>
<html>
<head>
	<title>Home Page</title>

	<link href="<c:url value="/resources/css/style.css" />" rel="stylesheet">
	<link href="<c:url value="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />" rel="stylesheet">
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.1.0.min.js"></script> 
	<script type="text/javascript" src="http://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script> 

</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<h1>
				Add/Edit a Person
			</h1>
		
			<c:url var="addAction" value="/add" ></c:url>
		
			<form:form action="${addAction}" commandName="person">
			<div class="form-group">
				<table>
					<tbody>
					<c:if test="${!empty person.name}">
					<tr>
						<td>
							<form:label path="id">
								<spring:message text="ID"/>
							</form:label>
						</td>
						<td>
							<form:input path="id" readonly="true"  class="form-control" size="8"  disabled="true" />
							<form:hidden path="id" />
						</td> 
					</tr>
					<br/>
					</c:if>
					</tbody>
					<tr>
						<td>
							<form:label path="Name">
								<spring:message text="Name"/>
							</form:label>
						</td>
						<td>
							<form:input path="name"  class="form-control" required="required" />
						</td> 
					</tr>
					
					<tr>
						<td>
							<form:label path="Surname">
								<spring:message text="Surname"/>
							</form:label>
						</td>
						<td>
							<form:input path="surname"  class="form-control" required="required"/>
						</td>
					</tr>
					
					<tr>
						<td>
							<form:label path="Birthday">
								<spring:message text="Birthday"/>
							</form:label>
						</td>
						<td>
							<form:input path="birthday"  class="form-control" type="date" required="required"/>
						</td>
					</tr>
					
					<tr>
						<td colspan="2">
							<c:if test="${!empty person.name}">
								<input type="submit"  class="btn btn-primary col-lg-offset-6"
									value="<spring:message text="Edit Person"/>" />
							</c:if>
							<c:if test="${empty person.name}">
								<input type="submit"  class="btn btn-primary col-lg-offset-6"
									value="<spring:message text="Add Person"/>" />
							</c:if>
						</td>
					</tr>
				</table>
				</div>	
			</form:form>
		</div>
		
		<div class="col-lg-6">
		
		<h1>Person Relatives</h1>
		
			<table class="tableStyle">
			<c:if test="${!empty findPersonRelatives}">
				<thead>
					<tr>
					<th width="120">Name</th>
					<th width="120">Surname</th>
					<th width="120">Birthday</th>
					</tr>
				</thead>	
			</c:if>
			<tbody>
				<c:forEach var="user" items="${findPersonRelatives}">
					
					<tr>
						<td>
							<c:out value="${user.name}"/>
						</td>
						<td>
							<c:out value="${user.surname}"/>
						</td>
						<td>
							<c:out value="${user.formattedBirthday}"/>
						</td>
					</tr>
					
				</c:forEach>
			</tbody>
				<c:if test="${empty findPersonRelatives}">
					no user selected.
				</c:if>
			</table>
		</div>
		
	</div>
	<br>
	<h3>Persons List</h3>
	<c:if test="${!empty findAll}">
		<table class="tableStyle sortable">
			<thead>
				<tr>
					<th width="120">Name</th>
					<th width="120">Surname</th>
					<th width="120">Birthday</th>
					<th width="60" class="sorttable_nosort">Edit</th>
					<th width="60" class="sorttable_nosort">Delete</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${findAll}" var="person">
					<tr>
						<td>${person.name}</td>
						<td>${person.surname}</td>
						<td>${person.formattedBirthday}</td>
						<td><a href="<c:url value='/edit/${person.id}' />" >Edit</a></td>
						<td><a href="<c:url value='/remove/${person.id}' />" >Delete</a></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</c:if>
</div>
<br/>
</body>
</html>